# Generated by Django 3.1.1 on 2020-10-10 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words_of_feelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reg', to='words_of_feelapp.registration'),
        ),
    ]
