# Generated by Django 3.1.1 on 2020-10-14 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words_of_feelapp', '0003_auto_20201010_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='user_mobile',
            field=models.PositiveIntegerField(default=1, verbose_name='Mobile Number'),
            preserve_default=False,
        ),
    ]
