# Generated by Django 3.1.1 on 2020-10-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words_of_feelapp', '0004_registration_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='user_mobile',
            field=models.PositiveIntegerField(max_length=10, verbose_name='Mobile Number'),
        ),
    ]
